### ISSUE TITLE
Allow dbt model selection based on provided path

### ISSUE THREAD

**Issue by wojciech-mazur-mlg** [preset-io/backend-sdk#217]
We would like to see dbt model selector based on provided path to run all models located in this path.

Example command:

`preset-cli superset sync dbt-core target/manifest.json --select models/subdirectory`

- It should work the same as for dbt, e.g.: `dbt compile --select models/subdirectory`
- `models/subdirectory` and `models/subdirectory/*` should be equivalent.

Currently it raises NotImplementedError and redirects to ticket creation.

It is somehow similar to issue: https://github.com/preset-io/backend-sdk/issues/171 but this tickets extends that one.

**Comment by Vitor-Avila** [comment]
@wojciech-mazur-mlg I just merged this PR that should implement this requirement: https://github.com/preset-io/backend-sdk/pull/242

As a heads up, using `models/subdirectory/*` directly wouldn't work because the terminal automatically unpacks the folder and adds all files as elements to the CLI command, which would fail since they don't have the `--select` flag to work properly. You can either use quotes (`"models/subdirectory/*"`) to implement this behavior, use `models/subdirectory` or `models/subdirectory/`.

Thanks!

**Comment by wojciech-mazur-mlg** [comment]
Thank you @Vitor-Avila !
